### PR TITLE
feat(main): allow the API to accept the package.json object

### LINKED ISSUE #8: Allow the JavaScript API to accept a package.json obect
Currently npm-scripts-info automatically loads the package json from the current working directory. This makes the module not reusable.

This change will allow to write a [mos](https://github.com/zkochan/mos) plugin for generating scripts documentation sections

I can make a pull request today with this update

### PR DESCRIPTION
**Pull request by zkochan**
close #8

### CODE REVIEW

**Comment by srph** [comment]
I think it should default to the cwd package.json if none is provided.

**Comment by zkochan** [comment]
ok, I'll update it

**Comment by srph** [comment]
lgtm :D. will release an update as soon as I connect to a stable wifi.

**Comment by zkochan** [comment]
Thanks

**Pull request merged**
